### ISSUE TITLE
Информация об установке и возможностях

### ISSUE THREAD

**Issue by Maxsior** [ENAleksey/etis-extension#4]
Привет, ребят!
Добавьте, пожалуйста в `README.md` общее описание расширения: что умеет, как установить, как начать работу, что планируется сделать - в общем, то, что должен видеть пользователь. То, что сейчас есть в README можно перенести в `CONTRIBUTION.md`, этот файл как раз должен содержать информацию для разработчиков о том, как контрибьютить и каких правил придерживаться.

**Comment by VladislavMaksimov** [comment]
@Maxsior, спасибо) Сделаем это в конце спринта.

**Comment by warmbl** [comment]
@Maxsior добавила руководство по установке.
